package com.person;  
   
import com.drools.test.Person;  

rule "boy"  
    salience 1  
    when  
        $p : Person(age > 0);  
    then  
        $p.setDesc("少年");  
        retract($p);  
end  
   
rule "youth"  
    salience 2  
    when  
        $p : Person(age > 12);  
    then  
        $p.setDesc("青年");  
        retract($p);  
end  
   
rule "midlife"  
    salience 3  
    when  
        $p : Person(age > 24);  
    then  
        $p.setDesc("中年");  
        retract($p);  
end  
   
rule "old"  
    salience 4  
    when  
        $p : Person(age > 60);  
    then  
        $p.setDesc("老年");  
        retract($p);  
end  