package   com.cisco.drools

import java.util.Map import com.cisco.eds.art.dto.shared.Request 
import com.cisco.eds.art.dto.shared.Resource import com.cisco.art.handler.DictionaryServiceHandler 
import com.cisco.art.handler.RequestServiceHandler import java.util.ArrayList rule"User_Termination_approveRule_approveRule_0_0"no-loop 
true ruleflow-group"group_User_Termination_approveRule_approveRule_0"
when $request:Request(eval("1"=="1"))then RequestServiceHandler.setStepNum($request.getRequestId(),1);
$request.setUserTaskName("SpecificUserList:changche,zhenghu,leol3,feiwa2,jiangulu,lijjin,sopxu,julizhou");
$request.setNeedApprove(true);
String aps=DictionaryServiceHandler.callApproveDictionary("SpecificUserList:changche,zhenghu,leol3,feiwa2,jiangulu,lijjin,sopxu,julizhou",
		$request.getRequester(),$request.getRequestId());$request.setApprovers(aps);
		System.out.println($request.getApprovers()+$request.isNeedApprove());end